### PR TITLE
deprecate this repo

### PR DESCRIPTION
**Pull request by lesv**

### CODE REVIEW

**Comment by frankyn** [comment]
Thanks Les

**Comment by tswast** [comment]
@elibixby Could you move to googlearchive?

P.S. I suppose we should get a DPE with permissions on googlearchive now that you're going on rotation.

**Comment by lesv** [comment]
@tswast This can now be deprecated again.

**Comment by lesv** [comment]
Actually, I found some usages. :(  I thought I got them all.

**Comment by tswast** [comment]
Okay, I'll wait to migrate. Ping me when you're ready to move it over to archives.

**Pull request merged**
